default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: dev
  password: dev
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: auth_service_development

test:
  <<: *default
  database: auth_service_test

production:
  <<: *default
  database: auth_service_production
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>